import crafttweaker.api.GenericRecipesManager;
import mods.jei.JEI;
import crafttweaker.api.text.ChatFormatting;

JEI.addDescription(<item:chemlib:helium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:lithium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:beryllium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:boron>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:carbon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:nitrogen>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:oxygen>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:fluorine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:neon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:sodium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:magnesium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:aluminum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:silicon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:phosphorus>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:sulfur>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:chlorine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:argon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:potassium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:calcium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:scandium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:titanium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:vanadium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:chromium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:manganese>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:iron>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:cobalt>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:nickel>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:copper>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:zinc>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:gallium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:germanium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:arsenic>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:selenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:bromine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:krypton>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:rubidium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:strontium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:yttrium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:zirconium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:niobium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:molybdenum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:technetium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:ruthenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:rhodium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:palladium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:silver>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:cadmium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:indium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:tin>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:antimony>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:tellurium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:iodine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:xenon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:cesium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:barium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:lanthanum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:cerium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:praseodymium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:neodymium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:promethium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:samarium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:europium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:gadolinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:terbium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:dysprosium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:holmium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:erbium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:thulium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:ytterbium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:lutetium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:hafnium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:tantalum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:tungsten>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:rhenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:osmium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:iridium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:platinum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:gold>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:mercury>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:thallium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:lead>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:bismuth>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:polonium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:astatine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:radon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:francium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:radium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:actinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:thorium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:protactinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:uranium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:neptunium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:plutonium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:americium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:curium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:berkelium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:californium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:einsteinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:fermium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:mendelevium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:nobelium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:lawrencium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:rutherfordium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:dubnium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:seaborgium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:bohrium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:hassium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:meitnerium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:darmstadtium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:roentgenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:copernicium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:nihonium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:flerovium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:moscovium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:livermorium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:tennessine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:oganesson>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");


JEI.hideCategory("jeresources:enchantment");

JEI.hideIngredient(<item:exnihilosequentia:andesite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:basalt_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:blackstone_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:diorite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:granite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:stone_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:iron_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:gold_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:copper_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:lead_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:tin_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:uranium_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:platinum_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:silver_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:zinc_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:nickel_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:oak_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:spruce_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:birch_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:blue_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:pink_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:purple_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:red_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:yellow_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:dust>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_netherrack>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_end_stone>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_andesite>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_diorite>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_granite>);
JEI.hideIngredient(<item:exnihilosequentia:blaze_doll>);
JEI.hideIngredient(<item:exnihilosequentia:enderman_doll>);
JEI.hideIngredient(<item:exnihilosequentia:shulker_doll>);
JEI.hideIngredient(<item:exnihilosequentia:guardian_doll>);
JEI.hideIngredient(<item:exnihilosequentia:bee_doll>);
JEI.hideIngredient(<item:exnihilosequentia:diamond_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:golden_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:iron_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:netherite_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:stone_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:wooden_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:acacia_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:jungle_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:end_cake>);
JEI.hideIngredient(<item:exnihilosequentia:jungle_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:oak_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:spruce_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:crimson_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:warped_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:dark_oak_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:birch_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:acacia_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:large_fern_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:string_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:flint_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:iron_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:diamond_mesh>); 
JEI.hideIngredient(<item:exnihilosequentia:emerald_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:netherite_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:fern_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:bamboo_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:pickle_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:kelp_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:sweet_berry_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:potato_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:carrot_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:sugarcane_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:cactus_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:dark_oak_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:mycelium_spores>);
JEI.hideIngredient(<item:exnihilosequentia:grass_seeds>);

JEI.hideIngredient(<item:ae2:facade>);
JEI.hideIngredient(<item:refinedstorage:cover>);
JEI.hideCategory("create:mystery_conversion");
JEI.hideCategory("reliquary:alkahestry_charging");
JEI.hideCategory("reliquary:alkahestry_crafting");

<item:chemlib:carbon>.addTooltip("§6Can be used as furnace fuel§r");
<item:chemlib:hydrogen>.addTooltip("§6Can be used as furnace fuel§r");
<item:kubejs:raw_andesite_alloy>.addTooltip("§6§kx§r §4Blood Thirsty§r §6§kx§r");
<item:kubejs:finished_program>.addTooltip("§b§k. §r§bGet back to reality...§r");